### ISSUE TITLE
Unhandled rejection ValidationError: The `revisions` instance is not valid. Details: `row_id` can't be blank (value: NaN).

### ISSUE THREAD

**Issue by dash-** [jouke/loopback-auditz#2]
Reproduced at this repository: https://github.com/dash-/loopback-auditz-example

```bash
git clone git@github.com:dash-/loopback-auditz-example.git
npm install
```

# Background:

node v7.0.0, node v7.2.0 (Mac OSX w/ nvm)
Datasource: "db", mongodb (fresh/empty db)

Key dependencies:
```javascript
    "loopback": "^2.22.0",
    "loopback-auditz": "^0.4.2",
    "loopback-boot": "^2.6.5",
    "loopback-component-remote-ctx": "^0.2.4",
    "loopback-connector-mongodb": "^1.17.0",
    "loopback-datasource-juggler": "^2.39.0",
```

Model mixins config:
```javascript
  "mixins": {
    "Auditz": true
  },
```

# Receiving an error upon startup (node .):

Unhandled rejection ValidationError: The `revisions` instance is not valid. Details: `row_id` can't be blank (value: NaN).
    at /Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/dao.js:322:12
    at ModelConstructor.<anonymous> (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/validations.js:492:11)
    at ModelConstructor.next (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/hooks.js:81:12)
    at ModelConstructor.<anonymous> (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/validations.js:489:23)
    at ModelConstructor.trigger (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/hooks.js:71:12)
    at ModelConstructor.Validatable.isValid (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/validations.js:455:8)
    at /Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/dao.js:318:9
    at doNotify (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:121:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:119:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/factorer/src/public/loopback-auditz-example/node_modules/loopback-datasource-juggler/lib/observer.js:119:15)

**Comment by dash-** [comment]
I think I've figured out the cause:  This module doesn't work with MongoDB because MongoDB uses non-numeric strings for IDs.

loopback-auditz/models/revision.json

```javascript
    ...
    "row_id": {
      "type": "Number",
      "comments": "The modelId affected",
      "required": true
    },
```

"type": "Number" should be "type": "String" for MongoDB, but that would obviously break it for most other databases.

A possible short term fix is to introduce a new config variable "revisions": { "model": ... } that would allow individuals to pass their own model (not just table name) to auditz to override the "Revision" model.  (If setting "name" to an alternate model is supposed to already work in this way, I sure couldn't get it to work)

Long term, it would probably be ideal to detect datasource connector for any given model and set the id type dynamically based on that, or at least allow users to provide an idType override in the config to change it from "Number" to "String."

**Comment by dash-** [comment]
I've created a fork that just has type: "String" for row_id, and it works.  I need it now, so I'm publishing to npm at https://www.npmjs.com/package/loopback-auditz-mongo

I'll be watching for the real fix, and will be deprecating my package once it's done.

**Comment by dash-** [comment]
Actually, I'm going to delete my module, and do something else entirely.  I can't get it to work, and I'm not sure about the licensing.

**Comment by jouke** [comment]
Thanks for reporting. I just reproduced the issue, and looking into it now.
What do you mean by 'I'm not sure about the licensing'? It's an OSI-approved ISC license...

**Comment by jouke** [comment]
Like you I see no other way around this than to define the row_id as a `String`. I've modified the tests accordingly, but your comment 

>  I can't get it to work, and I'm not sure about the licensing.

makes me a little unsure. Can you elaborate please?

**Comment by jouke** [comment]
Fixed in [this commit](https://github.com/jouke/loopback-auditz/commit/d6ef25cdfa9bd3d0106564e9f827c3334591534a) and published as version 0.5.0

You can now configure the idType for the revisions' model row_id property.

By the way, I've also added a test that proves setting another name for the revisions model works.

**Comment by dash-** [comment]
First, your turn-around is awesome.  I really appreciate that.  Props to you! 👍 

The license is fine, I just didn't look into it much and it didn't immediately look familiar (MIT, GNU, Apache).

However, I couldn't get it to work regardless, because there's another issue, which appears to be the reason the original had the _isDeleted field -- in Loopback w/ Mongo, there's no way to select by null.  So {where: {deletedAt: null}} won't return any records in Mongo, even when there's no deletedAt field.

I could open another issue if you'd like.  For now, I just rolled my own solution.  But it would definitely be preferable for me to use your package over a custom-built solution.

**Comment by dash-** [comment]
...
